package Diapositivas;

import static Diapositivas.InformacionFamilia.sesionUsuario;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

import javax.swing.WindowConstants;

import java.sql.*;
import Atajos.Conexion;
import Atajos.Salir;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniela
 */
public class Contraseña extends javax.swing.JFrame {

    String usuario;
    public static int sesionUsuario;
    /**
     * Creates new form Contraseña
     */
    public Contraseña() {
        initComponents();
        setSize(400, 400);
        setResizable(false);
        setLocationRelativeTo(null);
        
        usuario = Login.usuario;
        sesionUsuario = 1;
        setTitle("Cambio de contraseña - " + usuario);
        
        // cierre de frame
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        // colocar fondo de pantalla
        ImageIcon wallpaper = new ImageIcon("src/refugio/Login.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabelWallpaper.getWidth(), jLabelWallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabelWallpaper.setIcon(icono);
        this.repaint();
    }

    // colocar logo
      public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("refugio/loguito.png"));
        return retValue; 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        jLabelContra = new javax.swing.JLabel();
        textContra = new javax.swing.JTextField();
        jLabelContraRep = new javax.swing.JLabel();
        textConfirmacion = new javax.swing.JTextField();
        jButtonVolver = new javax.swing.JButton();
        jButtonCambiar = new javax.swing.JButton();
        jLabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getLogo());
        setIconImages(getIconImages());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 51));
        jLabelTitulo.setText("Cambio de contraseña");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 330, 30));

        jLabelUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUsuario.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(0, 0, 51));
        jLabelUsuario.setText("Usuario:");
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 330, 30));

        textUsuario.setBackground(new java.awt.Color(102, 102, 205));
        textUsuario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 200, -1));

        jLabelContra.setBackground(new java.awt.Color(0, 0, 0));
        jLabelContra.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabelContra.setForeground(new java.awt.Color(0, 0, 51));
        jLabelContra.setText("Contraseña nueva:");
        getContentPane().add(jLabelContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 330, 30));

        textContra.setBackground(new java.awt.Color(102, 102, 205));
        textContra.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(textContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 200, -1));

        jLabelContraRep.setBackground(new java.awt.Color(0, 0, 0));
        jLabelContraRep.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabelContraRep.setForeground(new java.awt.Color(0, 0, 51));
        jLabelContraRep.setText("Confirmación contraseña nueva:");
        getContentPane().add(jLabelContraRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 330, 30));

        textConfirmacion.setBackground(new java.awt.Color(102, 102, 205));
        textConfirmacion.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(textConfirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 200, -1));

        jButtonVolver.setBackground(new java.awt.Color(102, 102, 255));
        jButtonVolver.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setText("Volver atrás");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        jButtonCambiar.setBackground(new java.awt.Color(102, 102, 255));
        jButtonCambiar.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonCambiar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCambiar.setText("Cambiar contraseña");
        jButtonCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 200, 60));

        jLabelWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refugio/Login.jpg"))); // NOI18N
        getContentPane().add(jLabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -20, 520, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarActionPerformed

        String validacion, contraseñaNueva, confirmacion;
        int mensaje;
        
        validacion = textUsuario.getText().trim();
        contraseñaNueva = textContra.getText().trim();
        confirmacion = textConfirmacion.getText().trim();
        
        // verificación de que coincidan contraseñas
        if(contraseñaNueva.equals(confirmacion)){
            // aplicación de cambios según nombre usuario
            try{
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement("update personalrefugio "
                        + "set Contraseña=? where Usuario = '" + validacion + "'");
            
                mensaje = JOptionPane.showConfirmDialog(null, "¿Quierés cambiar "
                         + "la contraseña?");

                if(mensaje == 0){
                    pst.setString(1, contraseñaNueva);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Se ha cambiado la contraseña "
                        + "correspondiente a " + validacion);
                    cn.close();
                } else {
                    JOptionPane.showMessageDialog(null, "No se modificó la contraseña "
                        + "de " + validacion);
                    cn.close();
                }
            
       
            }catch(SQLException e){
                System.err.println("Error al cambiar contraseña " + e);
                JOptionPane.showMessageDialog(null, "No se pudo cambiar la contraseña");
            }
            
        } else{
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
        }
    }//GEN-LAST:event_jButtonCambiarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed

      Inicio inicio = new Inicio();
      inicio.setVisible(true);
      this.dispose();
        
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       
        Salir salir = new Salir();
        salir.botonCerrar();
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCambiar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelContra;
    private javax.swing.JLabel jLabelContraRep;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelWallpaper;
    private javax.swing.JTextField textConfirmacion;
    private javax.swing.JTextField textContra;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
