package Diapositivas;

// imports conexión a base de datos
import java.sql.*;
import Atajos.Conexion;
import Atajos.Salir;

// imports imágenes
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
/**
 *
 * @author Daniela
 */
public class InformacionGastos extends javax.swing.JFrame {

    String usuario;
    public static int sesionUsuario;
    /**
     * Creates new form InformacionGato
     */
    public InformacionGastos() {
        initComponents();
        setSize(920, 710);
        setResizable(false);
        setLocationRelativeTo(null);
        
        usuario = Login.usuario;
        sesionUsuario = 1;
        setTitle("Información del gato elegido - " + usuario);
        
        // cierre de frame
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        // colocar fondo de pantalla
        ImageIcon wallpaper = new ImageIcon("src/refugio/lineas-azules.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabelWallpaper.getWidth(), jLabelWallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabelWallpaper.setIcon(icono);
        this.repaint();
    }

    // colocar logo
      public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("refugio/loguito.png"));
        return retValue; 
    }
    
      
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        textNombreGato = new javax.swing.JTextField();
        jLabelEdadGato = new javax.swing.JLabel();
        textEdadGato = new javax.swing.JTextField();
        jLabelRazaGato = new javax.swing.JLabel();
        textRazaGato = new javax.swing.JTextField();
        jLabelDescripcionGato = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDescripcion = new javax.swing.JTextArea();
        jLabelPersonaACargo = new javax.swing.JLabel();
        textPersonaACargo = new javax.swing.JTextField();
        jLabelStatusGato = new javax.swing.JLabel();
        textStatus = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonBuscar = new javax.swing.JButton();
        textBuscar = new javax.swing.JTextField();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonVolverAtras = new javax.swing.JButton();
        jLabelNombre1 = new javax.swing.JLabel();
        textNombreGato1 = new javax.swing.JTextField();
        IDGato = new javax.swing.JLabel();
        textIDGato = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        textNumero = new javax.swing.JTextField();
        jLabelEstado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textEstado = new javax.swing.JTextArea();
        jLabelGastos = new javax.swing.JLabel();
        textGastos = new javax.swing.JTextField();
        jLabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getLogo());
        setIconImages(getIconImages());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Información del gato.");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 410, 110));

        jLabelNombre.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre del gato:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        textNombreGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textNombreGato.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textNombreGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, 30));

        jLabelEdadGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelEdadGato.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdadGato.setText("Edad del gato:");
        getContentPane().add(jLabelEdadGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        textEdadGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textEdadGato.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textEdadGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 150, 30));

        jLabelRazaGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelRazaGato.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRazaGato.setText("Raza del gato:");
        getContentPane().add(jLabelRazaGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        textRazaGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textRazaGato.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textRazaGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 150, 30));

        jLabelDescripcionGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelDescripcionGato.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescripcionGato.setText("Descripción/condiciones del gato:");
        getContentPane().add(jLabelDescripcionGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        textDescripcion.setColumns(20);
        textDescripcion.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textDescripcion.setForeground(new java.awt.Color(0, 102, 153));
        textDescripcion.setRows(5);
        jScrollPane1.setViewportView(textDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 280, -1));

        jLabelPersonaACargo.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelPersonaACargo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPersonaACargo.setText("Personal a cargo del gato:");
        getContentPane().add(jLabelPersonaACargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        textPersonaACargo.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textPersonaACargo.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textPersonaACargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 200, 30));

        jLabelStatusGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelStatusGato.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStatusGato.setText("Status del gato:");
        getContentPane().add(jLabelStatusGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        textStatus.setEditable(false);
        textStatus.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textStatus.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 270, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBuscar.setBackground(new java.awt.Color(102, 102, 255));
        jButtonBuscar.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscar.setText("Buscar gato");
        jButtonBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 200, -1));

        textBuscar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textBuscar.setForeground(new java.awt.Color(0, 102, 153));
        jPanel1.add(textBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 210, 30));

        jButtonModificar.setBackground(new java.awt.Color(102, 102, 255));
        jButtonModificar.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonModificar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificar.setText("Modificar registro.");
        jButtonModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 200, -1));

        jButtonEliminar.setBackground(new java.awt.Color(102, 102, 255));
        jButtonEliminar.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setText("Eliminar registro.");
        jButtonEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 200, -1));

        jButtonVolverAtras.setBackground(new java.awt.Color(102, 102, 255));
        jButtonVolverAtras.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonVolverAtras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolverAtras.setText("Volver atrás");
        jButtonVolverAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 870, 110));

        jLabelNombre1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelNombre1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre1.setText("Nombre del gato:");
        getContentPane().add(jLabelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, -1));

        textNombreGato1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textNombreGato1.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textNombreGato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 150, 30));

        IDGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        IDGato.setForeground(new java.awt.Color(255, 255, 255));
        IDGato.setText("ID del gato:");
        getContentPane().add(IDGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, -1));

        textIDGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textIDGato.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textIDGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 150, 30));

        jLabelNumero.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelNumero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumero.setText("Número de control:");
        getContentPane().add(jLabelNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, -1, -1));

        textNumero.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textNumero.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 150, 30));

        jLabelEstado.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelEstado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstado.setText("Revisiones/estado:");
        getContentPane().add(jLabelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, -1, -1));

        textEstado.setColumns(20);
        textEstado.setRows(5);
        jScrollPane2.setViewportView(textEstado);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 330, 180));

        jLabelGastos.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelGastos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGastos.setText("Gastos:");
        getContentPane().add(jLabelGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 600, -1, -1));

        textGastos.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textGastos.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 620, 150, 30));

        jLabelWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refugio/lineas-azules.jpg"))); // NOI18N
        getContentPane().add(jLabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 940, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAtrasActionPerformed

        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonVolverAtrasActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
       
       String busqueda, query_uno, query_dos;
       
       busqueda = textBuscar.getText().trim();
       
       query_uno = "select * from gatitos where NombreGato = '" + busqueda + "'";
       query_dos = "select * from control where NombreGato = '" + busqueda + "'";
       
       //conexión a la base para ver los datos
       try{
           Connection cn = Conexion.conectar();
           PreparedStatement pst1 = cn.prepareStatement(query_uno);
           PreparedStatement pst2 = cn.prepareStatement(query_dos);
           ResultSet rs1 = pst1.executeQuery();
           ResultSet rs2 = pst2.executeQuery();
           
           if(rs1.next()){
               // gatitos
               textNombreGato.setText(rs1.getString("NombreGato"));
               textEdadGato.setText(rs1.getString("Edad"));
               textRazaGato.setText(rs1.getString("Raza"));
               textDescripcion.setText(rs1.getString("Descripcion"));
               textPersonaACargo.setText(rs1.getString("PersonaACargo"));
               textStatus.setText(rs1.getString("Status"));
           }
           if(rs2.next()){
               // control
               textNombreGato1.setText(rs2.getString("NombreGato"));
               textIDGato.setText(rs2.getString("IDGato"));
               textNumero.setText(rs2.getString("NumeroControl"));
               textEstado.setText(rs2.getString("Estado"));
               textGastos.setText(rs2.getString("Gastos"));
           }
           cn.close();
           
       }catch(SQLException e){
           System.out.println("Error al buscar al gato " + e);
           JOptionPane.showMessageDialog(null, "No se pudo buscar al gato solicitado");
       }
     
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
       
       String busqueda;
       int alternativaMensaje;
       
       busqueda = textBuscar.getText().trim();
       
       // conexión a la base de datos para eliminar un registro solicitado
       try{
           Connection cn = Conexion.conectar();
           PreparedStatement pst = cn.prepareStatement("delete from gatitos where NombreGato = '" + busqueda + "'");
           PreparedStatement pst2 = cn.prepareStatement("delete from consulta where NombreGato = '" + busqueda + "'");
           
           // validación de alternativas del mensaje de confirmación
           alternativaMensaje = JOptionPane.showConfirmDialog(null, "Estás por eliminar un registro, "
                    + "¿está seguro de que quieres hacerlo?");
           
           if(alternativaMensaje == 0){
               pst.executeUpdate();
               pst2.executeUpdate();
               LimpiarCampos();
               JOptionPane.showMessageDialog(null, "Eliminación de registro "
                    + "éxitoso");
               cn.close();
           } else {
               cn.close();
               JOptionPane.showMessageDialog(null, "No se ha eliminado el registro");
           }
           
       }catch(SQLException e){
           System.err.println("Error al conectar con la base de datos para "
                   + "eliminar el registro solicitado " + e);
           JOptionPane.showMessageDialog(null, "Error al conectar con la base "
                   + "de datos para eliminar el registro solicitado");
       }

    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
       
        String busqueda, nombreMod, edadMod, razaMod, descripcionMod, personaMod, 
                statusMod, nombre, ID, numeroControl, revisiones, gastos, query_uno, query_dos;
        int alternativaMensaje;

        busqueda = textBuscar.getText().trim();
        
        // gatitos
        nombreMod = textNombreGato.getText().trim();
        edadMod = textEdadGato.getText().trim();
        razaMod = textRazaGato.getText().trim();
        descripcionMod = textDescripcion.getText().trim();
        personaMod = textPersonaACargo.getText().trim();
        statusMod = textStatus.getText().trim();
        
        // control
        nombre = textNombreGato1.getText().trim();
        ID = textIDGato.getText().trim();
        numeroControl= textNumero.getText().trim();
        revisiones = textEstado.getText().trim();
        gastos = textGastos.getText().trim();
        
        query_uno = "update gatitos set NombreGato=?, Edad=?, Raza=?, "
                + "Descripcion=?, PersonaACargo=?, Status=? where "
                + "NombreGato = '" + busqueda + "'";
        
        query_dos = "update control set NombreGato=?, IDGato=?, NumeroControl=?, Estado=?, "
                + "Gastos=? where NombreGato ='" + busqueda + "'";
        
        // conexión a la base de datos para modificar datos de un registro
        try{
            Connection cn = Conexion.conectar();
            PreparedStatement pst1 = cn.prepareStatement(query_uno);
            PreparedStatement pst2 = cn.prepareStatement(query_dos);
            
            // validación de alternativas del mensaje de confirmación
            alternativaMensaje = JOptionPane.showConfirmDialog(null, "¿Quieres modificar los datos?");
            
            if(alternativaMensaje == 0){
                // gatitos
                pst1.setString(1, nombreMod);
                pst1.setString(2, edadMod);
                pst1.setString(3, razaMod);
                pst1.setString(4, descripcionMod);
                pst1.setString(5, personaMod);
                pst1.setString(6, statusMod);
                
                // control
                pst2.setString(1, nombre);
                pst2.setString(2, ID);
                pst2.setString(3, numeroControl);
                pst2.setString(4, revisiones);
                pst2.setString(5, gastos);
            
                pst1.executeUpdate();
                pst2.executeUpdate();
                cn.close();
                JOptionPane.showMessageDialog(null, "Se han modificado los datos");
            } else {
                cn.close();
                JOptionPane.showMessageDialog(null, "No se modificaron los datos");
            }
            
        }catch(SQLException e){
            System.err.println("Error al modificar datos " + e);
            JOptionPane.showMessageDialog(null, "No se ha podido modificar la información "
                    + "del gato");
        }
        
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        Salir salir = new Salir();
        salir.botonCerrar();
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionGastos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDGato;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonVolverAtras;
    private javax.swing.JLabel jLabelDescripcionGato;
    private javax.swing.JLabel jLabelEdadGato;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelGastos;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelPersonaACargo;
    private javax.swing.JLabel jLabelRazaGato;
    private javax.swing.JLabel jLabelStatusGato;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelWallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField textBuscar;
    private javax.swing.JTextArea textDescripcion;
    private javax.swing.JTextField textEdadGato;
    private javax.swing.JTextArea textEstado;
    private javax.swing.JTextField textGastos;
    private javax.swing.JTextField textIDGato;
    private javax.swing.JTextField textNombreGato;
    private javax.swing.JTextField textNombreGato1;
    private javax.swing.JTextField textNumero;
    private javax.swing.JTextField textPersonaACargo;
    private javax.swing.JTextField textRazaGato;
    private javax.swing.JTextField textStatus;
    // End of variables declaration//GEN-END:variables

    public void LimpiarCampos(){
        // gatitos
        textNombreGato.setText("");
        textEdadGato.setText("");
        textRazaGato.setText("");
        textDescripcion.setText("");
        textPersonaACargo.setText("");
        textStatus.setText("");
        
        // conrol
        textNombreGato1.setText("");
        textIDGato.setText("");
        textNumero.setText("");
        textEstado.setText("");
        textGastos.setText("");
    }
}
