package Diapositivas;

// imports conexión a base de datos
import java.sql.*;
import Atajos.Conexion;
import Atajos.Salir;

// imports imágenes
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
/**
 *
 * @author Daniela
 */
public class InformacionFamilia extends javax.swing.JFrame {

    String usuario;
    public static int sesionUsuario;
    /**
     * Creates new form InformacionGato
     */
    public InformacionFamilia() {
        initComponents();
        setSize(920, 710);
        setResizable(false);
        setLocationRelativeTo(null);
        
        usuario = Login.usuario;
        sesionUsuario = 1;
        setTitle("Información de la familia - " + usuario);
        
        // cierre de frame
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        // colocar fondo de pantalla
        ImageIcon wallpaper = new ImageIcon("src/refugio/lineas-de-colores.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabelWallpaper.getWidth(), jLabelWallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabelWallpaper.setIcon(icono);
        this.repaint();
    }

    // colocar logo
      public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("refugio/loguito.png"));
        return retValue; 
    }
    
      
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelFamilia = new javax.swing.JLabel();
        textFamilia = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        textNombreGato = new javax.swing.JTextField();
        jLabelFecha = new javax.swing.JLabel();
        textFechaIngreso = new javax.swing.JTextField();
        jLabelDireccion = new javax.swing.JLabel();
        textDireccion = new javax.swing.JTextField();
        jLabelIDGato = new javax.swing.JLabel();
        textIDGato = new javax.swing.JTextField();
        jLabelIDFamilia = new javax.swing.JLabel();
        textIDFamilia = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonFamilia = new javax.swing.JButton();
        textBuscar = new javax.swing.JTextField();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonVolverAtras = new javax.swing.JButton();
        jLabelNombre1 = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textChequeos = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textComportamiento = new javax.swing.JTextArea();
        jLabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getLogo());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Información de la familia.");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 410, 110));

        jLabelFamilia.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelFamilia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFamilia.setText("Familia:");
        getContentPane().add(jLabelFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        textFamilia.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textFamilia.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 200, 30));

        jLabelNombre.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre nuevo:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        textNombreGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textNombreGato.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textNombreGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 200, 30));

        jLabelFecha.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelFecha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecha.setText("Fecha de ingreso:");
        getContentPane().add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        textFechaIngreso.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textFechaIngreso.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 200, 30));

        jLabelDireccion.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelDireccion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDireccion.setText("Dirección:");
        getContentPane().add(jLabelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        textDireccion.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textDireccion.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 200, 30));

        jLabelIDGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelIDGato.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIDGato.setText("ID gato:");
        getContentPane().add(jLabelIDGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        textIDGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textIDGato.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textIDGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 200, 30));

        jLabelIDFamilia.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelIDFamilia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIDFamilia.setText("ID familia:");
        getContentPane().add(jLabelIDFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        textIDFamilia.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textIDFamilia.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textIDFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 200, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonFamilia.setBackground(new java.awt.Color(102, 102, 255));
        jButtonFamilia.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonFamilia.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFamilia.setText("Buscar ID familia");
        jButtonFamilia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFamiliaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 200, -1));

        textBuscar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textBuscar.setForeground(new java.awt.Color(0, 102, 153));
        jPanel1.add(textBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 210, 30));

        jButtonModificar.setBackground(new java.awt.Color(102, 102, 255));
        jButtonModificar.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonModificar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificar.setText("Modificar registro.");
        jButtonModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 200, -1));

        jButtonEliminar.setBackground(new java.awt.Color(102, 102, 255));
        jButtonEliminar.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setText("Eliminar registro.");
        jButtonEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 200, -1));

        jButtonVolverAtras.setBackground(new java.awt.Color(102, 102, 255));
        jButtonVolverAtras.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonVolverAtras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolverAtras.setText("Volver atrás");
        jButtonVolverAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 870, 110));

        jLabelNombre1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelNombre1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre1.setText("Chequeos veterinarios:");
        getContentPane().add(jLabelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, -1));

        jLabelEstado.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelEstado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstado.setText("Comportamiento/adaptacíón:");
        getContentPane().add(jLabelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, -1, -1));

        textChequeos.setColumns(20);
        textChequeos.setRows(5);
        jScrollPane3.setViewportView(textChequeos);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 330, 140));

        textComportamiento.setColumns(20);
        textComportamiento.setRows(5);
        jScrollPane2.setViewportView(textComportamiento);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 330, 180));

        jLabelWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refugio/lineas-de-colores.jpg"))); // NOI18N
        getContentPane().add(jLabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 940, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAtrasActionPerformed

        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonVolverAtrasActionPerformed

    private void jButtonFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFamiliaActionPerformed
       
        String busqueda, query_uno, query_dos;
        
        busqueda = textBuscar.getText().trim();
        
        query_uno = "select * from adopciones where IDFamilia = '" + busqueda + "'";
        query_dos = "select * from seguimiento where IDFamilia = '" + busqueda + "'";
        
        try{
            Connection cn = Conexion.conectar();
            PreparedStatement pst1 = cn.prepareStatement(query_uno);
            PreparedStatement pst2 = cn.prepareStatement(query_dos);
            ResultSet rs1 = pst1.executeQuery();
            ResultSet rs2 = pst2.executeQuery();
            
            // adopciones
            if(rs1.next()){
               textFamilia.setText(rs1.getString("Familia"));
               textNombreGato.setText(rs1.getString("NombreNuevo"));
               textFechaIngreso.setText(rs1.getString("FechaIngreso"));
               textDireccion.setText(rs1.getString("Direccion"));
               textIDGato.setText(rs1.getString("IDGato"));
            }else{
                System.err.println("No se pudo conectar con adopciones");
            }
            
            // seguimiento
            if(rs2.next()){
               textIDFamilia.setText(rs2.getString("IDFamilia"));
               textChequeos.setText(rs2.getString("EstadoVet"));
               textComportamiento.setText(rs2.getString("Comportamiento"));
            } else{
                System.err.println("No se pudo conectar con adopciones");
            }
            
            cn.close();
        }catch(SQLException e){
            System.err.println("Error al conectar con la base de datos " + e);
            JOptionPane.showMessageDialog(null, "No pudimos conectar con la base de datos");
        }

    }//GEN-LAST:event_jButtonFamiliaActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
       
       String busqueda;
       int alternativaMensaje;
       
       busqueda = textBuscar.getText().trim();
       
       // conexión a la base de datos para eliminar un registro solicitado
       try{
           Connection cn = Conexion.conectar();
           PreparedStatement pst = cn.prepareStatement("delete from adopciones where Familia = '" + busqueda + "'");
           PreparedStatement pst2 = cn.prepareStatement("delete from seguimiento where Familia ='" + busqueda + "'");
           
           // validación de alternativas del mensaje de confirmación
           alternativaMensaje = JOptionPane.showConfirmDialog(null, "Estás por eliminar un registro, "
                    + "¿está seguro de que quieres hacerlo?");
           
           if(alternativaMensaje == 0){
               pst.executeUpdate();
               pst2.executeUpdate();
               LimpiarCampos();
               JOptionPane.showMessageDialog(null, "Eliminación de registro "
                    + "éxitoso");
               cn.close();
           } else {
               cn.close();
               JOptionPane.showMessageDialog(null, "No se ha eliminado el registro");
           }
           
       }catch(SQLException e){
           System.err.println("Error al conectar con la base de datos para "
                   + "eliminar el registro solicitado " + e);
           JOptionPane.showMessageDialog(null, "Error al conectar con la base "
                   + "de datos para eliminar el registro solicitado");
       }

    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
       
        String busqueda, familiaMod, nombreNMod, fechaMod, direccionMod, IDGatoMod, 
                statusMod, IDFamMod, chequeosMod, comportamientoMod, query_uno, query_dos;
        int alternativaMensaje;

        busqueda = textBuscar.getText().trim();
        
        // adopciones
        familiaMod = textFamilia.getText().trim();
        nombreNMod = textNombreGato.getText().trim();
        fechaMod = textFechaIngreso.getText().trim();
        direccionMod = textDireccion.getText().trim();
        IDGatoMod = textIDGato.getText().trim();
        
        // seguimiento
        IDFamMod = textIDFamilia.getText().trim();
        chequeosMod = textChequeos.getText().trim();
        comportamientoMod = textComportamiento.getText().trim();
        
        query_uno = "update adopciones set Familia=?, NombreNuevo=?, "
                + "FechaIngreso=?, Direccion=?, IDGato=? where Familia ='" + busqueda + "'";
        
        query_dos = "update seguimiento set Familia=?, NombreNuevo=?, EstadoVet=?, "
                + "Comportamiento=?, where Familia = '" + busqueda + "'";
        
        // conexión a la base de datos para modificar datos de un registro
        try{
            Connection cn = Conexion.conectar();
            PreparedStatement pst1 = cn.prepareStatement(query_uno);
            PreparedStatement pst2 = cn.prepareStatement(query_dos);
            
            // validación de alternativas del mensaje de confirmación
            alternativaMensaje = JOptionPane.showConfirmDialog(null, "¿Quieres modificar los datos?");
            
            if(alternativaMensaje == 0){
                // adopciones
                pst1.setString(1, familiaMod);
                pst1.setString(2, nombreNMod);
                pst1.setString(3, fechaMod);
                pst1.setString(4, direccionMod);
                pst1.setString(5, IDGatoMod);
                
                // seguimiento
                pst2.setString(1, familiaMod);
                pst2.setString(2, nombreNMod);
                pst2.setString(3, chequeosMod);
                pst2.setString(4, comportamientoMod);
                pst2.setString(5, IDFamMod);
            
                pst1.executeUpdate();
                pst2.executeUpdate();
                cn.close();
                JOptionPane.showMessageDialog(null, "Se han modificado los datos");
            } else {
                cn.close();
                JOptionPane.showMessageDialog(null, "No se modificaron los datos");
            }
            
        }catch(SQLException e){
            System.err.println("Error al modificar datos " + e);
            JOptionPane.showMessageDialog(null, "No se ha podido modificar la información "
                    + "del gato");
        }
        
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        Salir salir = new Salir();
        salir.botonCerrar();
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionFamilia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonFamilia;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonVolverAtras;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelFamilia;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelIDFamilia;
    private javax.swing.JLabel jLabelIDGato;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelWallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField textBuscar;
    private javax.swing.JTextArea textChequeos;
    private javax.swing.JTextArea textComportamiento;
    private javax.swing.JTextField textDireccion;
    private javax.swing.JTextField textFamilia;
    private javax.swing.JTextField textFechaIngreso;
    private javax.swing.JTextField textIDFamilia;
    private javax.swing.JTextField textIDGato;
    private javax.swing.JTextField textNombreGato;
    // End of variables declaration//GEN-END:variables

    public void LimpiarCampos(){
        // adopciones
        textFamilia.setText("");
        textNombreGato.setText("");
        textFechaIngreso.setText("");
        textDireccion.setText("");
        textIDGato.setText("");
        
        // seguimiento
        textIDFamilia.setText("");
        textChequeos.setText("");
        textComportamiento.setText("");
    }
}
