package Diapositivas;

// imports de diseño
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

// import de conexion base de datos
import java.sql.*;
import Atajos.Conexion;
import Atajos.Mensajes;
import Atajos.Salir;
import java.awt.Color;

import java.awt.event.KeyEvent;
import static javax.management.timer.Timer.ONE_SECOND;

import javax.swing.WindowConstants;

/**
 *
 * @author Daniela
 */
public class Login extends javax.swing.JFrame {

    public static String usuario = "", nombre = "", apellido = "";
    String contraseña = "";
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setSize(600, 640);
        setLayout(null);
        setResizable(false);
        setLocationRelativeTo(null);
          
        setTitle("Acceso al sistema");
       
        // fondo de pantalla
        ImageIcon wallpaper = new ImageIcon("src/refugio/Login.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabelWallpaper.getHeight(),
        jLabelWallpaper.getWidth(), Image.SCALE_DEFAULT));
        jLabelWallpaper.setIcon(icono);
        this.repaint();
        
        // logo 
        ImageIcon logo  = new ImageIcon("src/refugio/Huella2");
        Icon iconoLogo = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabelWallpaper.getHeight(), jLabelWallpaper.getWidth(), Image.SCALE_DEFAULT));
        jLabelWallpaper.setIcon(iconoLogo);
        this.repaint();
    }
    // icono
    public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("refugio/loguito.png"));
        return retValue;   
    }
    
    Mensajes mimensaje = new Mensajes();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelSubtitulo = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        textContraseña = new javax.swing.JPasswordField();
        jButtonIngreso = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelMensaje = new javax.swing.JLabel();
        jLabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Log in");
        setBackground(new java.awt.Color(0, 102, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getLogo());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refugio/Huella2.png"))); // NOI18N
        jLabelLogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 270, 210));

        jLabelTitulo.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 51));
        jLabelTitulo.setText("¡Bienvenido a refucat!");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 330, 30));

        jLabelSubtitulo.setBackground(new java.awt.Color(0, 0, 0));
        jLabelSubtitulo.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabelSubtitulo.setForeground(new java.awt.Color(0, 0, 51));
        jLabelSubtitulo.setText("Por favor inicia sesión.");
        getContentPane().add(jLabelSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 330, 30));

        textUsuario.setBackground(new java.awt.Color(102, 102, 205));
        textUsuario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 200, -1));

        textContraseña.setBackground(new java.awt.Color(102, 102, 205));
        textContraseña.setForeground(new java.awt.Color(255, 255, 255));
        textContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textContraseñaKeyPressed(evt);
            }
        });
        getContentPane().add(textContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 200, -1));

        jButtonIngreso.setBackground(new java.awt.Color(102, 102, 255));
        jButtonIngreso.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonIngreso.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIngreso.setText("Ingresar");
        jButtonIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, -1, -1));

        jButtonSalir.setBackground(new java.awt.Color(102, 102, 255));
        jButtonSalir.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, -1, -1));

        jLabelMensaje.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabelMensaje.setForeground(new java.awt.Color(242, 242, 242));
        getContentPane().add(jLabelMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 200, 30));

        jLabelWallpaper.setBackground(new java.awt.Color(0, 102, 153));
        jLabelWallpaper.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refugio/Login.jpg"))); // NOI18N
        jLabelWallpaper.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresoActionPerformed
       
        // Acceso al sistema
        usuario = textUsuario.getText().trim();
        contraseña = textContraseña.getText().trim();
  
        if(!usuario.equals("") && !contraseña.equals("")){
       
            try{
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement("select Nombre, Apellido from personalrefugio "
                      + "where Usuario = '" + usuario + "' and Contraseña = '" + contraseña + "'");
                ResultSet rs = pst.executeQuery();
                
                if(rs.next()){
                    nombre = rs.getString("Nombre");
                    apellido = rs.getString("Apellido");
                    mimensaje.DatosCorrectos(jLabelMensaje, "Ingresando al sistema");
                    this.dispose();
                    
                } else{
                    mimensaje.DatosIncorrectos(jLabelMensaje, "Datos incorrectos");
                    System.out.println("Datos incorrectos");
                    textUsuario.setText("");
                    textContraseña.setText(""); 
                }
                
            }catch(SQLException e){
                System.out.println("Error en el inicio de sesión: " + e);
            }
            
        }else{
            System.out.println("Por favor, completa todos los campos");
            textUsuario.setText("");
            textContraseña.setText("");
        }
    }//GEN-LAST:event_jButtonIngresoActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        
        Salir salir = new Salir();
        salir.botonCerrar();
        
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void textContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textContraseñaKeyPressed
      
        // creación de evento de teclado para ingresar con enter.
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            // Acceso al sistema
        
            usuario = textUsuario.getText().trim();
            contraseña = textContraseña.getText().trim();
        
            if(!usuario.equals("") && !contraseña.equals("")){
       
                try{
                    Connection cn = Conexion.conectar();
                    PreparedStatement pst = cn.prepareStatement("select Nombre, Apellido from personalrefugio "
                            + "where Usuario = '" + usuario + "' and Contraseña = '" + contraseña + "'");
                    ResultSet rs = pst.executeQuery();
                
                    
                    if(rs.next()){
                        Inicio inicio = new Inicio();
                        inicio.setVisible(true);
                        this.dispose();
                    } else{
                        mimensaje.DatosIncorrectos(jLabelMensaje, "Datos incorrectos");
                        System.out.println("Datos incorrectos");
                        textUsuario.setText("");
                        textContraseña.setText("");
                    }
                
                }catch(SQLException e){
                    System.out.println("Error en el inicio de sesión: " + e);
                }

            }  else{
                System.out.println("Por favor, completa todos los campos");
                textUsuario.setText("");
                textContraseña.setText(""); 
            }
        
        }
        
    }//GEN-LAST:event_textContraseñaKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
              
        Salir salir = new Salir();
        salir.botonCerrar();
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngreso;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelSubtitulo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelWallpaper;
    private javax.swing.JPasswordField textContraseña;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
    

}
