package Diapositivas;

import static Diapositivas.Inicio.sesionUsuario;
import Atajos.Conexion;
import Atajos.Salir;
import java.awt.Color;

// conexión
import java.sql.*;

// imports imágenes
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

// import pestaña
import javax.swing.WindowConstants;

/**
 *
 * @author Daniela
 */
public class RegistrarCuidador extends javax.swing.JFrame {

    String usuario = "";
    public static int sesionUsuario;
    /**
     * Creates new form RegistrarGatos
     */
    public RegistrarCuidador() {
        initComponents();
        setSize(800, 680);
        
        usuario = Login.usuario;
        sesionUsuario = 1;
        setTitle("Registro de cuidadores - " + usuario);
        setResizable(false);
        setLocationRelativeTo(null);
        
        // cierre de frame anterior
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
      
        // colocar imágenes
        ImageIcon fondo = new ImageIcon("src/refugio/espirales-de-colores.jpg");
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(jLabelWallpaper.getHeight(), 
        jLabelWallpaper.getWidth(), Image.SCALE_DEFAULT));
        jLabelWallpaper.setIcon(icono);
        this.repaint();
    }
    public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("refugio/loguito.png"));
        return retValue; 
    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        textNombreEmpleado = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        textApellido = new javax.swing.JTextField();
        jLabelUsuario = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        jLabelContraseña = new javax.swing.JLabel();
        textContraseña = new javax.swing.JPasswordField();
        jLabelStatusCuidador = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        jButtonVolverAtras = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonVerGatos = new javax.swing.JButton();
        jButtonVerCuidadores = new javax.swing.JButton();
        jButtonRegistrarCuidador = new javax.swing.JButton();
        jLabelDireccion = new javax.swing.JLabel();
        textDireccion = new javax.swing.JTextField();
        jLabelCantidad = new javax.swing.JLabel();
        textCantidad = new javax.swing.JTextField();
        jLabelCapacidad = new javax.swing.JLabel();
        textCapacidad = new javax.swing.JTextField();
        jLabelIDPersonal = new javax.swing.JLabel();
        textIDP = new javax.swing.JTextField();
        jLabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getLogo());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Registrar cuidador");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 410, 110));

        jLabelNombre.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre del cuidador:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        textNombreEmpleado.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textNombreEmpleado.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, 30));

        jLabelApellido.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellido.setText("Apellido del cuidador:");
        getContentPane().add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        textApellido.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textApellido.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, 30));

        jLabelUsuario.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario:");
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        textUsuario.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textUsuario.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 150, 30));

        jLabelContraseña.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContraseña.setText("Contraseña:");
        getContentPane().add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));
        getContentPane().add(textContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 150, 30));

        jLabelStatusCuidador.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelStatusCuidador.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStatusCuidador.setText("Status del cuidador:");
        getContentPane().add(jLabelStatusCuidador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        cmbStatus.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbStatus.setForeground(new java.awt.Color(0, 102, 153));
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo", " " }));
        getContentPane().add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 270, 30));

        jButtonVolverAtras.setBackground(new java.awt.Color(102, 102, 255));
        jButtonVolverAtras.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonVolverAtras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolverAtras.setText("Volver atras");
        jButtonVolverAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 200, -1));

        jButtonSalir.setBackground(new java.awt.Color(102, 102, 255));
        jButtonSalir.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir del sistema");
        jButtonSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 200, -1));

        jButtonVerGatos.setBackground(new java.awt.Color(102, 102, 255));
        jButtonVerGatos.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonVerGatos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerGatos.setText("Ver gatos");
        jButtonVerGatos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVerGatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerGatosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerGatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 200, -1));

        jButtonVerCuidadores.setBackground(new java.awt.Color(102, 102, 255));
        jButtonVerCuidadores.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonVerCuidadores.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerCuidadores.setText("Ver cuidadores");
        jButtonVerCuidadores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVerCuidadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerCuidadoresActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerCuidadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 200, -1));

        jButtonRegistrarCuidador.setBackground(new java.awt.Color(102, 102, 255));
        jButtonRegistrarCuidador.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonRegistrarCuidador.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrarCuidador.setText("Registrar cuidador");
        jButtonRegistrarCuidador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRegistrarCuidador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarCuidadorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrarCuidador, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 200, 100));

        jLabelDireccion.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelDireccion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDireccion.setText("Dirección:");
        getContentPane().add(jLabelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        textDireccion.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textDireccion.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 150, 30));

        jLabelCantidad.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidad.setText("Cantidad de gatos a cargo:");
        getContentPane().add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        textCantidad.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textCantidad.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 150, 30));

        jLabelCapacidad.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelCapacidad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCapacidad.setText("Capacidad hogar:");
        getContentPane().add(jLabelCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        textCapacidad.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textCapacidad.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 150, 30));

        jLabelIDPersonal.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelIDPersonal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIDPersonal.setText("ID personal:");
        getContentPane().add(jLabelIDPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        textIDP.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textIDP.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textIDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 150, 30));

        jLabelWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refugio/espirales-de-colores.jpg"))); // NOI18N
        getContentPane().add(jLabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -70, 2000, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAtrasActionPerformed

        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();
  
    }//GEN-LAST:event_jButtonVolverAtrasActionPerformed

    private void jButtonRegistrarCuidadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarCuidadorActionPerformed

        // declaración variables
        int status, avanzar = 0;
        String nombre, apellido, usuario, contraseña, statusNivel = null, 
                direccion, cantidad, capacidad, ID;
        
        // obtener valores
        nombre = textNombreEmpleado.getText().trim();
        apellido = textApellido.getText().trim();
        usuario = textUsuario.getText().trim();
        contraseña = textContraseña.getText().trim();
        status = cmbStatus.getSelectedIndex() + 1;
        
        direccion = textDireccion.getText().trim();
        cantidad = textCantidad.getText().trim();
        capacidad = textCapacidad.getText().trim();
        ID = textIDP.getText().trim();
        
         // verificación de que no haya campos sin completador.
        if(nombre.equals("")){
            textNombreEmpleado.setBackground(Color.red);
            avanzar++;
        }if(apellido.equals("")){
            textApellido.setBackground(Color.red);
            avanzar++;
        }if(usuario.equals("")){
            textUsuario.setBackground(Color.red);
            avanzar++;
        }if(contraseña.equals("")){
            textContraseña.setBackground(Color.red);
            avanzar++;
        }
    
        // verificación de la base de datos de datoscuidador
        if(direccion.equals("")){
            textDireccion.setBackground(Color.red);
            avanzar++;
        }
        if(cantidad.equals("")){
            textCantidad.setBackground(Color.red);
            avanzar++;
        }
        if(capacidad.equals("")){
            textCapacidad.setBackground(Color.red);
            avanzar++;
        }
        if(ID.equals("")){
            textIDP.setBackground(Color.red);
            avanzar++;
        }
        

        // dar valor al cmb de status
        if(status == 1){
            statusNivel = "Activo";
        }else if (status == 2){
            statusNivel = "Inactivo";
        }
        
        // cargar datos en la base de datos
        if(avanzar == 0){
        
            try{
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement("insert into personalrefugio values (?, ?, ?, ?, ?, ?)");
                PreparedStatement pst2 = cn.prepareStatement("insert into datoscuidador values (?, ?, ?, ?, ?, ?)");
               
                    // base personalrefugio
                    pst.setInt(1, 0);
                    pst.setString(2, nombre);
                    pst.setString(3, apellido);
                    pst.setString(4, usuario);
                    pst.setString(5, contraseña);
                    pst.setString(6, statusNivel);
                    
                    // base datoscuidador
                    pst2.setInt(1, 0);
                    pst2.setString(2, nombre);
                    pst2.setString(3, direccion);
                    pst2.setString(4, cantidad);
                    pst2.setString(5, capacidad);
                    pst2.setString(6, ID);
                    
                    pst.executeQuery();
                    pst2.executeQuery();
                    cn.close();
           
                    // vacío de campos
                    VaciarCampos();
                    
                    JOptionPane.showMessageDialog(null, "Has registrado un cuidador");
                    
            }catch(SQLException e){
                System.out.println("No se ha podido registrar al cuidador " + e);
                JOptionPane.showMessageDialog(null, "No se ha podido registrar al cuidador, "
                        + "por favor, contactese con el programador para solucionar"
                        + "el problema a la brevedad");
            }
        
        }else{    
            JOptionPane.showMessageDialog(null, "Debes completar todos los campos");
        }
        
    }//GEN-LAST:event_jButtonRegistrarCuidadorActionPerformed

    private void jButtonVerGatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerGatosActionPerformed
        
        VerGatos verGatos = new VerGatos();
        verGatos.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonVerGatosActionPerformed

    private void jButtonVerCuidadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerCuidadoresActionPerformed
       
        VerCuidadores verCuidadores = new VerCuidadores();
        verCuidadores.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonVerCuidadoresActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed

        Salir salir = new Salir();
        salir.botonCerrar();
        
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       
        Salir salir = new Salir();
        salir.botonCerrar();
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarCuidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarCuidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarCuidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarCuidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarCuidador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JButton jButtonRegistrarCuidador;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVerCuidadores;
    private javax.swing.JButton jButtonVerGatos;
    private javax.swing.JButton jButtonVolverAtras;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCapacidad;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelIDPersonal;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelStatusCuidador;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelWallpaper;
    private javax.swing.JTextField textApellido;
    private javax.swing.JTextField textCantidad;
    private javax.swing.JTextField textCapacidad;
    private javax.swing.JPasswordField textContraseña;
    private javax.swing.JTextField textDireccion;
    private javax.swing.JTextField textIDP;
    private javax.swing.JTextField textNombreEmpleado;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables

public void VaciarCampos(){
    // personalrefugio
    textNombreEmpleado.setText("");
    textApellido.setText("");
    textUsuario.setText("");
    textContraseña.setText("");
    cmbStatus.setSelectedIndex(0);
    
    // datoscuidador
    textDireccion.setText("");
    textCantidad.setText("");
    textCapacidad.setText("");
    textIDP.setText("");
}
}
