package Diapositivas;

import static Diapositivas.Inicio.sesionUsuario;
import Atajos.Conexion;
import Atajos.Salir;
import java.awt.Color;

// conexión
import java.sql.*;

// imports imágenes
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

// import pestaña
import javax.swing.WindowConstants;

/**
 *
 * @author Daniela
 */
public class RegistrarGatos extends javax.swing.JFrame {

    String usuario = "";
    public static int sesionUsuario;
    /**
     * Creates new form RegistrarGatos
     */
    public RegistrarGatos() {
        initComponents();
        setSize(800, 640);
        
        usuario = Login.usuario;
        sesionUsuario = 1;
        setTitle("Registro de gatos - " + usuario);
        setResizable(false);
        setLocationRelativeTo(null);
        
        // cierre de frame anterior
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
      
        // colocar imágenes
        ImageIcon fondo = new ImageIcon("src/refugio/lineas-azules.jpg");
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(jLabelWallpaper.getHeight(), 
        jLabelWallpaper.getWidth(), Image.SCALE_DEFAULT));
        jLabelWallpaper.setIcon(icono);
        this.repaint();
    }
    public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("refugio/loguito.png"));
        return retValue; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        textNombreGato = new javax.swing.JTextField();
        jLabelEdadGato = new javax.swing.JLabel();
        textEdadGato = new javax.swing.JTextField();
        jLabelSexo = new javax.swing.JLabel();
        textSexo = new javax.swing.JTextField();
        jLabelRazaGato = new javax.swing.JLabel();
        textRazaGato = new javax.swing.JTextField();
        jLabelDescripcionGato = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDescripcion = new javax.swing.JTextArea();
        jLabelPersonaACargo = new javax.swing.JLabel();
        textPersonaACargo = new javax.swing.JTextField();
        jLabelStatusGato = new javax.swing.JLabel();
        cmbStatusGato = new javax.swing.JComboBox<>();
        jButtonVolverAtras = new javax.swing.JButton();
        jButtonRegistrarGatos = new javax.swing.JButton();
        jButtonVerGatos = new javax.swing.JButton();
        jButtonVerCuidadores = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getLogo());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Registrar gatos");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 410, 110));

        jLabelNombre.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre del gato:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        textNombreGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textNombreGato.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textNombreGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, 30));

        jLabelEdadGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelEdadGato.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdadGato.setText("Edad del gato:");
        getContentPane().add(jLabelEdadGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        textEdadGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textEdadGato.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textEdadGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, 30));

        jLabelSexo.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelSexo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSexo.setText("Sexo del gato:");
        getContentPane().add(jLabelSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        textSexo.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textSexo.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 150, 30));

        jLabelRazaGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelRazaGato.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRazaGato.setText("Raza del gato:");
        getContentPane().add(jLabelRazaGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        textRazaGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textRazaGato.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textRazaGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 150, 30));

        jLabelDescripcionGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelDescripcionGato.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescripcionGato.setText("Descripción/condiciones del gato:");
        getContentPane().add(jLabelDescripcionGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        textDescripcion.setColumns(20);
        textDescripcion.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textDescripcion.setForeground(new java.awt.Color(0, 102, 153));
        textDescripcion.setRows(5);
        jScrollPane1.setViewportView(textDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 280, -1));

        jLabelPersonaACargo.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelPersonaACargo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPersonaACargo.setText("Personal a cargo del gato:");
        getContentPane().add(jLabelPersonaACargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        textPersonaACargo.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textPersonaACargo.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textPersonaACargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 200, 30));

        jLabelStatusGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelStatusGato.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStatusGato.setText("Status del gato:");
        getContentPane().add(jLabelStatusGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        cmbStatusGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbStatusGato.setForeground(new java.awt.Color(0, 102, 153));
        cmbStatusGato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rescatado en buen estado", "Rescatado en mal estado", "Rescatado en embarazo", "Rescatado y con necesidad de madre", "Buen estado", "Mal estado", "Embarazo", "Necesita de una madre", "Adoptado", "Fallecido" }));
        getContentPane().add(cmbStatusGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 270, 30));

        jButtonVolverAtras.setBackground(new java.awt.Color(102, 102, 255));
        jButtonVolverAtras.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonVolverAtras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolverAtras.setText("Volver atras");
        jButtonVolverAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 200, -1));

        jButtonRegistrarGatos.setBackground(new java.awt.Color(102, 102, 255));
        jButtonRegistrarGatos.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonRegistrarGatos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrarGatos.setText("Registrar gato");
        jButtonRegistrarGatos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRegistrarGatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarGatosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrarGatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 200, 100));

        jButtonVerGatos.setBackground(new java.awt.Color(102, 102, 255));
        jButtonVerGatos.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonVerGatos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerGatos.setText("Ver gatos");
        jButtonVerGatos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVerGatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerGatosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerGatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 200, -1));

        jButtonVerCuidadores.setBackground(new java.awt.Color(102, 102, 255));
        jButtonVerCuidadores.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonVerCuidadores.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerCuidadores.setText("Ver cuidadores");
        jButtonVerCuidadores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVerCuidadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerCuidadoresActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerCuidadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 200, -1));

        jButtonSalir.setBackground(new java.awt.Color(102, 102, 255));
        jButtonSalir.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir del sistema");
        jButtonSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 200, -1));

        jLabelWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refugio/lineas-azules.jpg"))); // NOI18N
        getContentPane().add(jLabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -70, 2000, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAtrasActionPerformed

        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();
  
    }//GEN-LAST:event_jButtonVolverAtrasActionPerformed

    private void jButtonRegistrarGatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarGatosActionPerformed

        // declaración variables
        int status, avanzar = 0;
        String nombreGato, edad, sexo, raza, descripcion, personaACargo, statusNivel = null;
        
        // obtener valores
        nombreGato = textNombreGato.getText().trim();
        edad = textEdadGato.getText().trim();
        sexo = textSexo.getText().trim();
        raza = textRazaGato.getText().trim();
        descripcion = textDescripcion.getText().trim();
        personaACargo = textPersonaACargo.getText().trim();
        status = cmbStatusGato.getSelectedIndex() + 1;
        
         // verificación de que no haya campos sin completador.
        if(nombreGato.equals("")){
            textNombreGato.setBackground(Color.red);
            avanzar++;
        }if(edad.equals("")){
            textEdadGato.setBackground(Color.red);
            avanzar++;
        }if(sexo.equals("")){
            textSexo.setBackground(Color.red);
            avanzar++;
        }if(raza.equals("")){
            textRazaGato.setBackground(Color.red);
            avanzar++;
        }if(personaACargo.equals("")){
            textPersonaACargo.setBackground(Color.red);
            avanzar++;
        }
        
        // dar valor al cmb de status
        if(status == 1){
            statusNivel = "Rescatado en buen estado";
        }else if (status == 2){
            statusNivel = "Rescatado en mal estado";
        }else if (status == 3){
            statusNivel = "Rescatada en embarazo";
        }else if (status == 4){
            statusNivel = "Rescatado y con necesidad de madre";
        }else if (status == 5){
            statusNivel = "Buen estado";
        }else if (status == 6){
            statusNivel = "Mal estado";
        }else if (status == 7){
            statusNivel = "Embarazo";
        }else if (status == 8){
            statusNivel = "Necesita de una madre";
        }else if (status == 9){
            statusNivel = "Adoptado";
        }else if (status == 10){
            statusNivel = "Fallecido";
        }
       
        
        // cargar datos en la base de datos
        if(avanzar == 0){
        
            try{
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement("insert into gatitos values (?, ?, ?, ?, ?, ?, ?, ?)");
               
                    pst.setInt(1, 0);
                    pst.setString(2, nombreGato);
                    pst.setString(3, edad);
                    pst.setString(4, sexo);
                    pst.setString(5, raza);
                    pst.setString(6, descripcion);
                    pst.setString(7, personaACargo);
                    pst.setString(8, statusNivel);
                    
                    pst.executeUpdate();
                    cn.close();
           
                    // vacío de campos
                    VaciarCampos();
                    
                    JOptionPane.showMessageDialog(null, "Has registrado un gatito");
                    
            }catch(SQLException e){
                System.out.println("No se ha podido registrar al gato " + e);
                JOptionPane.showMessageDialog(null, "No se ha podido registrar al gato, "
                        + "por favor, contactese con el programador para solucionar"
                        + "el problema a la brevedad");
            }
        
        }else{    
            JOptionPane.showMessageDialog(null, "Debes completar todos los campos");
        }
        
    }//GEN-LAST:event_jButtonRegistrarGatosActionPerformed

    private void jButtonVerGatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerGatosActionPerformed
        
        VerGatos verGatos = new VerGatos();
        verGatos.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonVerGatosActionPerformed

    private void jButtonVerCuidadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerCuidadoresActionPerformed
       
        VerCuidadores verCuidadores = new VerCuidadores();
        verCuidadores.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonVerCuidadoresActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed

        Salir salir = new Salir();
        salir.botonCerrar();
        
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        Salir salir = new Salir();
        salir.botonCerrar();
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarGatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarGatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarGatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarGatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarGatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbStatusGato;
    private javax.swing.JButton jButtonRegistrarGatos;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVerCuidadores;
    private javax.swing.JButton jButtonVerGatos;
    private javax.swing.JButton jButtonVolverAtras;
    private javax.swing.JLabel jLabelDescripcionGato;
    private javax.swing.JLabel jLabelEdadGato;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPersonaACargo;
    private javax.swing.JLabel jLabelRazaGato;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelStatusGato;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelWallpaper;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textDescripcion;
    private javax.swing.JTextField textEdadGato;
    private javax.swing.JTextField textNombreGato;
    private javax.swing.JTextField textPersonaACargo;
    private javax.swing.JTextField textRazaGato;
    private javax.swing.JTextField textSexo;
    // End of variables declaration//GEN-END:variables

public void VaciarCampos(){
    textNombreGato.setText("");
    textEdadGato.setText("");
    textRazaGato.setText("");
    textDescripcion.setText("");
    textPersonaACargo.setText("");
    cmbStatusGato.setSelectedIndex(0);
}
}
