package Diapositivas;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

import java.sql.*;
import Atajos.Conexion;
import Atajos.Salir;

import javax.swing.JOptionPane;

import javax.swing.WindowConstants;

/**
 *
 * @author Daniela
 */
public class Veterinario extends javax.swing.JFrame {

    String usuario;
    public static int sesionUsuario;
    /**
     * Creates new form Veterinario
     */
    public Veterinario() {
        initComponents();
        setSize(800, 640);
        setLocationRelativeTo(null);
        setResizable(false);
        
        usuario = Login.usuario;
        sesionUsuario = 1;
        setTitle("Control veterinario - " + usuario);
        
        // cierre de frame
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        // colocar fondo de pantalla
        ImageIcon wallpaper = new ImageIcon("src/refugio/luces-azules.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabelWallpaper.getWidth(), jLabelWallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabelWallpaper.setIcon(icono);
        this.repaint();

    }
     // colocar logo
     public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("refugio/loguito.png"));
        return retValue; 
     }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        textNombreGato = new javax.swing.JTextField();
        IDGato = new javax.swing.JLabel();
        textIDGato = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        textNumero = new javax.swing.JTextField();
        jLabelEstado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textEstado = new javax.swing.JTextArea();
        jLabelGastos = new javax.swing.JLabel();
        textGastos = new javax.swing.JTextField();
        jButtonVolverAtras = new javax.swing.JButton();
        jButtonVerControles = new javax.swing.JButton();
        jButtonControlRegistro = new javax.swing.JButton();
        jLabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getLogo());
        setIconImages(getIconImages());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Controles veterinarios.");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 410, 110));

        jLabelNombre.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre del gato:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        textNombreGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textNombreGato.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textNombreGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, 30));

        IDGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        IDGato.setForeground(new java.awt.Color(255, 255, 255));
        IDGato.setText("ID del gato:");
        getContentPane().add(IDGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        textIDGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textIDGato.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textIDGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, 30));

        jLabelNumero.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelNumero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumero.setText("Número de control:");
        getContentPane().add(jLabelNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        textNumero.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textNumero.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 150, 30));

        jLabelEstado.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelEstado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstado.setText("Revisiones/estado:");
        getContentPane().add(jLabelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        textEstado.setColumns(20);
        textEstado.setRows(5);
        jScrollPane1.setViewportView(textEstado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 440, 230));

        jLabelGastos.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelGastos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGastos.setText("Gastos:");
        getContentPane().add(jLabelGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        textGastos.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textGastos.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 150, 30));

        jButtonVolverAtras.setBackground(new java.awt.Color(102, 102, 255));
        jButtonVolverAtras.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonVolverAtras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolverAtras.setText("Volver atras");
        jButtonVolverAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 200, -1));

        jButtonVerControles.setBackground(new java.awt.Color(102, 102, 255));
        jButtonVerControles.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonVerControles.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerControles.setText("Controles registrados");
        jButtonVerControles.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVerControles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerControlesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerControles, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 200, -1));

        jButtonControlRegistro.setBackground(new java.awt.Color(102, 102, 255));
        jButtonControlRegistro.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonControlRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jButtonControlRegistro.setText("Nuevo control");
        jButtonControlRegistro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonControlRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonControlRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonControlRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 200, 100));

        jLabelWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refugio/luces-azules.jpg"))); // NOI18N
        getContentPane().add(jLabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -50, 960, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAtrasActionPerformed

        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonVolverAtrasActionPerformed

    private void jButtonControlRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonControlRegistroActionPerformed

        String nombreGato, ID, numeroControl, revisiones, gastos;
        int avanzar = 0;
        
        nombreGato = textNombreGato.getText().trim();
        ID = textIDGato.getText().trim();
        numeroControl= textNumero.getText().trim();
        revisiones = textEstado.getText().trim();
        gastos = textGastos.getText().trim();
        
        // verificación de campos completos
        if(nombreGato.equals("")){
            textNombreGato.setBackground(Color.red);
            avanzar++;
        }
        if(ID.equals("")){
            textIDGato.setBackground(Color.red);
            avanzar++;
        }
        if(numeroControl.equals("")){
            textNumero.setBackground(Color.red);
            avanzar++;
        }
        if(revisiones.equals("")){
            textEstado.setBackground(Color.red);
            avanzar++;
        }
        if(gastos.equals("")){
            textGastos.setBackground(Color.red);
            avanzar++;
        }
                
        
        if(avanzar == 0){
            try{
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement("insert into control "
                        + "values (?, ?, ?, ?, ?, ?)");
                
                pst.setInt(1, 0);
                pst.setString(2, nombreGato);
                pst.setString(3, ID);
                pst.setString(4, numeroControl);
                pst.setString(5, revisiones);
                pst.setString(6, gastos);
                
                pst.executeUpdate();
                cn.close();
                
                JOptionPane.showMessageDialog(null, "Se generó el registro solicitado");
                LimpiarCampos();
                
            }catch(SQLException e){
                System.err.println("No se pudo registrar la consulta veterinaria " + e);
                JOptionPane.showMessageDialog(null, "No se pudo registrar la "
                        + "consulta veterinaria");
            }
        }
    }//GEN-LAST:event_jButtonControlRegistroActionPerformed

    private void jButtonVerControlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerControlesActionPerformed

        VerControles controles = new VerControles();
        controles.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonVerControlesActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
              
        Salir salir = new Salir();
        salir.botonCerrar();
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Veterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Veterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Veterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Veterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Veterinario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDGato;
    private javax.swing.JButton jButtonControlRegistro;
    private javax.swing.JButton jButtonVerControles;
    private javax.swing.JButton jButtonVolverAtras;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelGastos;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelWallpaper;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textEstado;
    private javax.swing.JTextField textGastos;
    private javax.swing.JTextField textIDGato;
    private javax.swing.JTextField textNombreGato;
    private javax.swing.JTextField textNumero;
    // End of variables declaration//GEN-END:variables

    public void LimpiarCampos(){
        textNombreGato.setText("");
        textIDGato.setText("");
        textNumero.setText("");
        textEstado.setText("");
        textGastos.setText("");
    }
}

