package Diapositivas;

// imports conexión a base de datos
import java.sql.*;
import Atajos.Conexion;

// imports imágenes
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
/**
 *
 * @author Daniela
 */
public class InformacionCuidador extends javax.swing.JFrame {

    String usuario;
    public static int sesionUsuario;
    /**
     * Creates new form InformacionGato
     */
    public InformacionCuidador() {
        initComponents();
        setSize(920, 710);
        setResizable(false);
        setLocationRelativeTo(null);
        
        usuario = Login.usuario;
        sesionUsuario = 1;
        setTitle("Información del cuidador - " + usuario);
        
        // cierre de frame
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        // colocar fondo de pantalla
        ImageIcon wallpaper = new ImageIcon("src/refugio/fondoazulcuadritos.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabelWallpaper.getWidth(), jLabelWallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabelWallpaper.setIcon(icono);
        this.repaint();
    }

    // colocar logo
      public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("refugio/loguito.png"));
        return retValue; 
    }
    
      
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        textApellido = new javax.swing.JTextField();
        jLabelUsuario = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        textStatus = new javax.swing.JTextField();
        jLabelDireccion = new javax.swing.JLabel();
        textDireccion = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonCuidador = new javax.swing.JButton();
        textBuscar = new javax.swing.JTextField();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonVolverAtras = new javax.swing.JButton();
        jLabelCantidad = new javax.swing.JLabel();
        textCantidad = new javax.swing.JTextField();
        jLabelCapacidad = new javax.swing.JLabel();
        textCapacidad = new javax.swing.JTextField();
        jLabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getLogo());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Información del cuidador.");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 410, 110));

        jLabelNombre.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        textNombre.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textNombre.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 200, 30));

        jLabelApellido.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellido.setText("Apellido:");
        getContentPane().add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        textApellido.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textApellido.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 200, 30));

        jLabelUsuario.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario:");
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        textUsuario.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textUsuario.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 200, 30));

        jLabelStatus.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStatus.setText("Status:");
        getContentPane().add(jLabelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        textStatus.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textStatus.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 200, 30));

        jLabelDireccion.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelDireccion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDireccion.setText("Dirección:");
        getContentPane().add(jLabelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, -1));

        textDireccion.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textDireccion.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 200, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCuidador.setBackground(new java.awt.Color(102, 102, 255));
        jButtonCuidador.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonCuidador.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCuidador.setText("Buscar por nombre");
        jButtonCuidador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCuidador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuidadorActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCuidador, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 200, -1));

        textBuscar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textBuscar.setForeground(new java.awt.Color(0, 102, 153));
        jPanel1.add(textBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 210, 30));

        jButtonModificar.setBackground(new java.awt.Color(102, 102, 255));
        jButtonModificar.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonModificar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificar.setText("Modificar registro.");
        jButtonModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 200, -1));

        jButtonEliminar.setBackground(new java.awt.Color(102, 102, 255));
        jButtonEliminar.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setText("Eliminar registro.");
        jButtonEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 200, -1));

        jButtonVolverAtras.setBackground(new java.awt.Color(102, 102, 255));
        jButtonVolverAtras.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonVolverAtras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolverAtras.setText("Volver atrás");
        jButtonVolverAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 870, 110));

        jLabelCantidad.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidad.setText("Cantidad de gatos a cargo:");
        getContentPane().add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, -1));

        textCantidad.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textCantidad.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 200, 30));

        jLabelCapacidad.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelCapacidad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCapacidad.setText("Capacidad:");
        getContentPane().add(jLabelCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, -1, -1));

        textCapacidad.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textCapacidad.setForeground(new java.awt.Color(0, 102, 153));
        getContentPane().add(textCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 200, 30));

        jLabelWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refugio/fondoazulcuadritos.jpg"))); // NOI18N
        getContentPane().add(jLabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 940, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAtrasActionPerformed

        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonVolverAtrasActionPerformed

    private void jButtonCuidadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuidadorActionPerformed
       
       String busqueda, query_uno, query_dos;
       
       busqueda = textBuscar.getText().trim();
       
       query_uno = "select * from personalrefugio where Nombre = '" + busqueda + "'";
       query_dos = "select * from datoscuidador where Nombre ='" + busqueda + "'";
        
       try{
           Connection cn = Conexion.conectar();
           PreparedStatement pst1 = cn.prepareStatement(query_uno);
           PreparedStatement pst2 = cn.prepareStatement(query_dos);
           ResultSet rs1 = pst1.executeQuery();
           ResultSet rs2 = pst2.executeQuery();
           
           // personalrefugio
           if(rs1.next()){
               textNombre.setText(rs1.getString("Nombre"));
               textApellido.setText(rs1.getString("Apellido"));
               textUsuario.setText(rs1.getString("Usuario"));
               textStatus.setText(rs1.getString("Status"));
           }else{
               System.err.println("Error al conectar con personalrefugio");
           }
           
           // datoscuidador
           if(rs2.next()){
               textDireccion.setText(rs2.getString("Direccion"));
               textCantidad.setText(rs2.getString("GatosACargo"));
               textCapacidad.setText(rs2.getString("Capacidad"));
           }else{
               System.err.println("Error al conectar con datoscuidador");
           }
           
           cn.close();
           
       }catch(SQLException e){
           System.err.println("Error al conectar con la base de datos " + e);
           JOptionPane.showMessageDialog(null, "No se pudo conectar con la base de datos");
       }
       
    }//GEN-LAST:event_jButtonCuidadorActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
       
       String busqueda;
       int alternativaMensaje;
       
       busqueda = textBuscar.getText().trim();
       
       // conexión a la base de datos para eliminar un registro solicitado
       try{
           Connection cn = Conexion.conectar();
           PreparedStatement pst1 = cn.prepareStatement("delete from personalrefugio where Nombre = '" + busqueda + "'");
           PreparedStatement pst2 = cn.prepareStatement("delete from datoscuidador where Nombre = '" + busqueda + "'");
           
           // validación de alternativas del mensaje de confirmación
           alternativaMensaje = JOptionPane.showConfirmDialog(null, "Estás por eliminar un registro, "
                    + "¿está seguro de que quieres hacerlo?");
           
           if(alternativaMensaje == 0){
               pst1.executeUpdate();
               pst2.executeUpdate();
               LimpiarCampos();
               JOptionPane.showMessageDialog(null, "Eliminación de registro "
                    + "éxitoso");
               cn.close();
           } else {
               cn.close();
               JOptionPane.showMessageDialog(null, "No se ha eliminado el registro");
           }
           
       }catch(SQLException e){
           System.err.println("Error al conectar con la base de datos para "
                   + "eliminar el registro solicitado " + e);
           JOptionPane.showMessageDialog(null, "Error al conectar con la base "
                   + "de datos para eliminar el registro solicitado");
       }

    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
       
        String busqueda, nombreMod, apellidoMod, usuarioMod, direccionMod, 
                statusMod, cantidadMod, capacidadMod, query_uno, query_dos;
        
        int alternativaMensaje;

        busqueda = textBuscar.getText().trim();
        
        // personalrefugio
        nombreMod = textNombre.getText().trim();
        apellidoMod = textApellido.getText().trim();
        usuarioMod = textUsuario.getText().trim();
        statusMod = textStatus.getText().trim();
        
        // datoscuidador
        direccionMod = textDireccion.getText().trim();
        cantidadMod = textCantidad.getText().trim();
        capacidadMod = textCapacidad.getText().trim();
        
        query_uno = "update personalrefugio set Nombre=?, Apellido=?, "
                + "Usuario=?, Status=? where Nombre ='" + busqueda + "'";
        
        query_dos = "update datoscuidador set Nombre=?, Direccion=?, GatosACargo=?, "
                + "Capacidad=? where Familia = '" + busqueda + "'";
        
        // conexión a la base de datos para modificar datos de un registro
        try{
            Connection cn = Conexion.conectar();
            PreparedStatement pst1 = cn.prepareStatement(query_uno);
            PreparedStatement pst2 = cn.prepareStatement(query_dos);
            
            // validación de alternativas del mensaje de confirmación
            alternativaMensaje = JOptionPane.showConfirmDialog(null, "¿Quieres modificar los datos?");
            
            if(alternativaMensaje == 0){
                // personalrefugio
                pst1.setString(1, nombreMod);
                pst1.setString(2, apellidoMod);
                pst1.setString(3, usuarioMod);
                pst1.setString(4, statusMod);
                
                // datoscuidador
                pst2.setString(1, nombreMod);
                pst2.setString(2, direccionMod);
                pst2.setString(3, cantidadMod);
                pst2.setString(4, capacidadMod);
            
                pst1.executeUpdate();
                pst2.executeUpdate();
                cn.close();
                JOptionPane.showMessageDialog(null, "Se han modificado los datos");
            } else {
                cn.close();
                JOptionPane.showMessageDialog(null, "No se modificaron los datos");
            }
            
        }catch(SQLException e){
            System.err.println("Error al modificar datos " + e);
            JOptionPane.showMessageDialog(null, "No se ha podido modificar la información "
                    + "del gato");
        }
        
    }//GEN-LAST:event_jButtonModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionCuidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionCuidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionCuidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionCuidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionCuidador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCuidador;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonVolverAtras;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCapacidad;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelWallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textApellido;
    private javax.swing.JTextField textBuscar;
    private javax.swing.JTextField textCantidad;
    private javax.swing.JTextField textCapacidad;
    private javax.swing.JTextField textDireccion;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textStatus;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables

    public void LimpiarCampos(){
        // personalrefugio
        textNombre.setText("");
        textApellido.setText("");
        textUsuario.setText("");
        textStatus.setText("");
        
        // datoscuidador
        textDireccion.setText("");
        textCantidad.setText("");
        textCapacidad.setText("");
    }
}
