package Diapositivas;

// imports conexión
import java.sql.*;
import Atajos.Conexion;

// import para sacar usuario
import Diapositivas.Login;

// import imagenes
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;

// import para cerrar pestaña anterior
import javax.swing.WindowConstants;
/**
 *
 * @author Daniela
 */
public class Inicio extends javax.swing.JFrame {

    String nombre, usuario;
    public static int sesionUsuario;
    
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setSize(600, 570);
        
        usuario = Login.usuario;
        sesionUsuario = 1;
        setTitle("Menú de inicio - " + usuario);
        setResizable(false);
        setLocationRelativeTo(null);
        
        // cierre de frame anterior
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
      
        // colocar imágenes
        ImageIcon wallpaper = new ImageIcon("src/refugio/curvas.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabelWallpaper.getHeight(), 
        jLabelWallpaper.getWidth(), Image.SCALE_DEFAULT));
        jLabelWallpaper.setIcon(icono);
        this.repaint();
        
        // nombre en el título
        try{
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select Nombre, Apellido from personalrefugio where usuario= '" + usuario + "'");
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                String nombreEmpleado = rs.getString("Nombre");
                String apellidoEmpleado = rs.getString("Apellido");
                jLabelTitulo.setText("¡Bienvenido " + nombreEmpleado + " " + apellidoEmpleado + "!");
            }
        }catch(SQLException e){
            System.out.println("No ha sido posible recolectar los datos de la base " + e);
        }
        
    }
    
    public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("refugio/loguito.png"));
        return retValue; 
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelGatoMirandoIzq = new javax.swing.JLabel();
        jLabelGatoColgando = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonRegistrarGatos = new javax.swing.JButton();
        jButtonVerGatos = new javax.swing.JButton();
        jButtonRegistrarCuidador = new javax.swing.JButton();
        jButtonVerCuidador = new javax.swing.JButton();
        jButtonFamilias = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getLogo());
        setMinimumSize(new java.awt.Dimension(600, 600));
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 340, 50));

        jLabelGatoMirandoIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refugio/gatomirandoIzq.png"))); // NOI18N
        getContentPane().add(jLabelGatoMirandoIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 190, 320));

        jLabelGatoColgando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refugio/gatocolgando1.png"))); // NOI18N
        getContentPane().add(jLabelGatoColgando, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 290, 140));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegistrarGatos.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jButtonRegistrarGatos.setText("Registrar gatos.");
        jButtonRegistrarGatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarGatosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegistrarGatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 40));

        jButtonVerGatos.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jButtonVerGatos.setText("Ver gatos registrados.");
        jButtonVerGatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerGatosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVerGatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 260, 40));

        jButtonRegistrarCuidador.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jButtonRegistrarCuidador.setText("Registrar cuidador.");
        jButtonRegistrarCuidador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarCuidadorActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegistrarCuidador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 260, 40));

        jButtonVerCuidador.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jButtonVerCuidador.setText("Ver cuidadores.");
        jButtonVerCuidador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerCuidadorActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVerCuidador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 260, 40));

        jButtonFamilias.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jButtonFamilias.setText("Familias.");
        jButtonFamilias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFamiliasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFamilias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 260, 40));

        jButtonSalir.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jButtonSalir.setText("Salir.");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 260, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 300, 520));

        jLabelWallpaper.setForeground(new java.awt.Color(0, 51, 102));
        jLabelWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refugio/curvas.jpg"))); // NOI18N
        getContentPane().add(jLabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 620, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        
        System.exit(0);
        
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonRegistrarCuidadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarCuidadorActionPerformed
     
        RegistrarCuidador registrarCuidador = new RegistrarCuidador();
        registrarCuidador.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonRegistrarCuidadorActionPerformed

    private void jButtonRegistrarGatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarGatosActionPerformed
     
        RegistrarGatos registrarGatos = new RegistrarGatos();
        registrarGatos.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonRegistrarGatosActionPerformed

    private void jButtonVerGatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerGatosActionPerformed
       
        VerGatos verGatos = new VerGatos();
        verGatos.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonVerGatosActionPerformed

    private void jButtonVerCuidadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerCuidadorActionPerformed

        VerCuidadores verCuidadores = new VerCuidadores();
        verCuidadores.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonVerCuidadorActionPerformed

    private void jButtonFamiliasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFamiliasActionPerformed

        Familias familias = new Familias();
        familias.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonFamiliasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFamilias;
    private javax.swing.JButton jButtonRegistrarCuidador;
    private javax.swing.JButton jButtonRegistrarGatos;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVerCuidador;
    private javax.swing.JButton jButtonVerGatos;
    private javax.swing.JLabel jLabelGatoColgando;
    private javax.swing.JLabel jLabelGatoMirandoIzq;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelWallpaper;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
