package Diapositivas;

// imports conexion con frames
import Atajos.Conexion;
import static Diapositivas.RegistrarGatos.sesionUsuario;

// imports eventos
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

// imports conexión
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

// imports imágenes
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import java.awt.Toolkit;
import java.awt.Image;

// imports tabla
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import javax.swing.WindowConstants;


/**
 *
 * @author Daniela
 * 
 */
public class VerCuidadores extends javax.swing.JFrame {

    String usuario = "";
    public static int sesionUsuario;
    /**
     * Creates new form VerGatos
     */
    public VerCuidadores() {
        initComponents();
        setSize(900, 640);
        setResizable(false);
        setLocationRelativeTo(null);
        
        usuario = Login.usuario;
        sesionUsuario = 1;
        
        setTitle("Cuidadores registrados en sistema - " + usuario);
        
        // cierre de frame anterior
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
      
        // colocar imágenes
        ImageIcon fondo = new ImageIcon("src/refugio/ondas.jpg");
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(jLabelWallpaper.getHeight(), 
        jLabelWallpaper.getWidth(), Image.SCALE_DEFAULT));
        jLabelWallpaper.setIcon(icono);
        this.repaint();
        
        /* dos métodos declarados abajo: uno para cargar los datos en la tabla
         y otro para que los datos puedan visualizarse en los textfields. 
        */
        cargarDatos();
        obtencionDatosDeTabla();
        
    }
    // colocar logo
    public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("refugio/loguito.png"));
        return retValue; 
    }
 
    // método para cargar datos en la tabla
    private void cargarDatos(){
       
         DefaultTableModel model = new DefaultTableModel();
         
         try{
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select IDPersonal, Nombre, "
                    + "Apellido, Status from personalRefugio");
            ResultSet rs = pst.executeQuery();
            
            jTableCuidadores = new JTable(model);
            jScrollPane1.setViewportView(jTableCuidadores);
            
            model.addColumn("ID");
            model.addColumn("Nombre");
            model.addColumn("Apellido");
            model.addColumn("Status");
                
            while(rs.next()){
                Object[] fila = new Object [4];
                for(int i= 0; i < 4; i++){
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            cn.close();
 
        }catch(SQLException e){
            System.out.println("No es posible ver la lista de gatos: " + e);
            JOptionPane.showMessageDialog(null, "No se pudo recuperar datos de la lista,"
                    + "contactese con el programador");
        }


    }
    // método para poner los datos de la tabla en los textfields.
     public void obtencionDatosDeTabla(){
    
        jTableCuidadores.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent Mouse_evt){
                
                JTable tabCuid = (JTable) Mouse_evt.getSource();
                Point point = Mouse_evt.getPoint();
    
                int filaSeleccionada = tabCuid.rowAtPoint(point);

                if(Mouse_evt.getClickCount() == 1){
                  textNombre.setText(jTableCuidadores.getValueAt(jTableCuidadores.getSelectedRow(), 1).toString());
                  textApellidos.setText(jTableCuidadores.getValueAt(jTableCuidadores.getSelectedRow(), 2).toString());
                  textStatus.setText(jTableCuidadores.getValueAt(jTableCuidadores.getSelectedRow(), 3).toString());
                }
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jButtonVolverAtras = new javax.swing.JButton();
        jButtonRegistrarCuidadores = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCuidadores = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        textApellidos = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        textStatus = new javax.swing.JTextField();
        jLabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getLogo());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Ver cuidadores registrados");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 450, 110));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));

        jButtonSalir.setBackground(new java.awt.Color(102, 102, 255));
        jButtonSalir.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir del sistema");
        jButtonSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonVolverAtras.setBackground(new java.awt.Color(102, 102, 255));
        jButtonVolverAtras.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonVolverAtras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolverAtras.setText("Volver atras");
        jButtonVolverAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAtrasActionPerformed(evt);
            }
        });

        jButtonRegistrarCuidadores.setBackground(new java.awt.Color(102, 102, 255));
        jButtonRegistrarCuidadores.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonRegistrarCuidadores.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrarCuidadores.setText("Registrar cuidadores");
        jButtonRegistrarCuidadores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRegistrarCuidadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarCuidadoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRegistrarCuidadores, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(628, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonVolverAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRegistrarCuidadores)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 840, 140));

        jScrollPane1.setViewportBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTableCuidadores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102)));
        jTableCuidadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID ", "Nombre", "Apellido", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCuidadores.setCellSelectionEnabled(true);
        jTableCuidadores.setEnabled(false);
        jScrollPane1.setViewportView(jTableCuidadores);
        jTableCuidadores.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 257, 470, 320));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));

        jLabelNombre.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre:");

        textNombre.setEditable(false);
        textNombre.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textNombre.setForeground(new java.awt.Color(0, 102, 153));

        jLabelApellido.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellido.setText("Apellido:");

        textApellidos.setEditable(false);
        textApellidos.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textApellidos.setForeground(new java.awt.Color(0, 102, 153));

        jLabelStatus.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStatus.setText("Status:");

        textStatus.setEditable(false);
        textStatus.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textStatus.setForeground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelApellido)
                        .addComponent(textNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(textApellidos))
                    .addComponent(jLabelStatus)
                    .addComponent(textStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textApellidos)
                .addGap(18, 18, 18)
                .addComponent(jLabelStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 310, 280));

        jLabelWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refugio/lineas-de-colores.jpg"))); // NOI18N
        getContentPane().add(jLabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed

        System.exit(0);

    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAtrasActionPerformed

        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonVolverAtrasActionPerformed

    private void jButtonRegistrarCuidadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarCuidadoresActionPerformed
      
        RegistrarCuidador registrarCuidador = new RegistrarCuidador();
        registrarCuidador.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonRegistrarCuidadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerCuidadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerCuidadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerCuidadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerCuidadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerCuidadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrarCuidadores;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVolverAtras;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelWallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCuidadores;
    private javax.swing.JTextField textApellidos;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textStatus;
    // End of variables declaration//GEN-END:variables

}