package Diapositivas;

// imports conexion con frames
import Atajos.Conexion;
import static Diapositivas.RegistrarGatos.sesionUsuario;

// imports eventos
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

// imports conexión
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

// imports imagenes
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import java.awt.Toolkit;
import java.awt.Image;

// imports tabla
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import javax.swing.WindowConstants;


/**
 *
 * @author Daniela
 * 
 */
public class VerGatos extends javax.swing.JFrame {

    String usuario = "";
    public static int sesionUsuario;
    /**
     * Creates new form VerGatos
     */
    public VerGatos() {
        initComponents();
        setSize(900, 640);
        setResizable(false);
        setLocationRelativeTo(null);
        
        usuario = Login.usuario;
        sesionUsuario = 1;
        
        setTitle("Gatos registrados en sistema - " + usuario);
        
        // cierre de frame anterior
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
      
        // colocar imágenes
        ImageIcon fondo = new ImageIcon("src/refugio/lineas-de-colores.jpg");
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(jLabelWallpaper.getHeight(), 
        jLabelWallpaper.getWidth(), Image.SCALE_DEFAULT));
        jLabelWallpaper.setIcon(icono);
        this.repaint();
        
        /* dos métodos declarados abajo: uno para cargar los datos en la tabla
         y otro para que los datos puedan visualizarse en los textfields. 
        */
        
        cargarDatos();
        obtencionDatosDeTabla();
        
    }
    // colocar logo
    public Image getLogo(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("refugio/loguito.png"));
        return retValue; 
    }
 
    // método para cargar datos en la tabla
    private void cargarDatos(){
       
         DefaultTableModel model = new DefaultTableModel();
         
         try{
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select IDGato, NombreGato,"
                    + " Edad, Raza, PersonaACargo, Status from gatitos");
            ResultSet rs = pst.executeQuery();
            
            jTableGatos = new JTable(model);
            jScrollPane1.setViewportView(jTableGatos);
            
            model.addColumn("ID");
            model.addColumn("Nombre");
            model.addColumn("Edad");
            model.addColumn("Raza");
            model.addColumn("Cuidador");
            model.addColumn("Status");
                
            while(rs.next()){
                Object[] fila = new Object [6];
                for(int i= 0; i < 6; i++){
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            cn.close();
 
        }catch(SQLException e){
            System.out.println("No es posible ver la lista de gatos: " + e);
            JOptionPane.showMessageDialog(null, "No se pudo recuperar datos de la lista,"
                    + "contactese con el programador");
        }


    }
    // método para poner los datos de la tabla en los textfields.
     public void obtencionDatosDeTabla(){
    
        jTableGatos.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent Mouse_evt){
                
                JTable tabGat = (JTable) Mouse_evt.getSource();
                Point point = Mouse_evt.getPoint();
    
                int filaSeleccionada = tabGat.rowAtPoint(point);

                if(Mouse_evt.getClickCount() == 1){
                  textNombre.setText(jTableGatos.getValueAt(jTableGatos.getSelectedRow(), 1).toString());
                  textCuidador.setText(jTableGatos.getValueAt(jTableGatos.getSelectedRow(), 2).toString());
                  textEdadGato.setText(jTableGatos.getValueAt(jTableGatos.getSelectedRow(), 3).toString());
                  textRaza.setText(jTableGatos.getValueAt(jTableGatos.getSelectedRow(), 4).toString());
                  textStatus.setText(jTableGatos.getValueAt(jTableGatos.getSelectedRow(), 5).toString());
                }
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jButtonVolverAtras = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jLabelPersonaACargo = new javax.swing.JLabel();
        textCuidador = new javax.swing.JTextField();
        jLabelEdad = new javax.swing.JLabel();
        textEdadGato = new javax.swing.JTextField();
        jLabelRaza = new javax.swing.JLabel();
        textRaza = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        textStatus = new javax.swing.JTextField();
        jButtonRegistrarGatos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGatos = new javax.swing.JTable();
        jLabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getLogo());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Ver gatos registrados");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 410, 110));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));

        jButtonSalir.setBackground(new java.awt.Color(102, 102, 255));
        jButtonSalir.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir del sistema");
        jButtonSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonVolverAtras.setBackground(new java.awt.Color(102, 102, 255));
        jButtonVolverAtras.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonVolverAtras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolverAtras.setText("Volver atras");
        jButtonVolverAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAtrasActionPerformed(evt);
            }
        });

        jLabelNombre.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre del gato:");

        textNombre.setEditable(false);
        textNombre.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textNombre.setForeground(new java.awt.Color(0, 102, 153));

        jLabelPersonaACargo.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelPersonaACargo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPersonaACargo.setText("Cuidador:");

        textCuidador.setEditable(false);
        textCuidador.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textCuidador.setForeground(new java.awt.Color(0, 102, 153));

        jLabelEdad.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelEdad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdad.setText("Edad:");

        textEdadGato.setEditable(false);
        textEdadGato.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textEdadGato.setForeground(new java.awt.Color(0, 102, 153));

        jLabelRaza.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelRaza.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRaza.setText("Raza:");

        textRaza.setEditable(false);
        textRaza.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textRaza.setForeground(new java.awt.Color(0, 102, 153));

        jLabelStatus.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStatus.setText("Status:");

        textStatus.setEditable(false);
        textStatus.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        textStatus.setForeground(new java.awt.Color(0, 102, 153));

        jButtonRegistrarGatos.setBackground(new java.awt.Color(102, 102, 255));
        jButtonRegistrarGatos.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jButtonRegistrarGatos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrarGatos.setText("Registrar gatos");
        jButtonRegistrarGatos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRegistrarGatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarGatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRegistrarGatos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(173, 173, 173)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNombre)
                        .addGap(36, 36, 36)
                        .addComponent(jLabelPersonaACargo)
                        .addGap(70, 70, 70)
                        .addComponent(jLabelEdad)
                        .addGap(35, 35, 35)
                        .addComponent(jLabelRaza))
                    .addComponent(jLabelStatus)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textStatus, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textCuidador, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textEdadGato, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonVolverAtras)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRegistrarGatos)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEdad)
                            .addComponent(jLabelPersonaACargo)
                            .addComponent(jLabelRaza)
                            .addComponent(jLabelNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textCuidador)
                            .addComponent(textEdadGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textRaza))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 840, 140));

        jScrollPane1.setViewportBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTableGatos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102)));
        jTableGatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Gato", "Nombre", "Edad", "Raza", "Cuidador", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableGatos.setCellSelectionEnabled(true);
        jTableGatos.setEnabled(false);
        jScrollPane1.setViewportView(jTableGatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 257, 840, 340));

        jLabelWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refugio/lineas-de-colores.jpg"))); // NOI18N
        getContentPane().add(jLabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed

        System.exit(0);

    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAtrasActionPerformed

        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonVolverAtrasActionPerformed

    private void jButtonRegistrarGatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarGatosActionPerformed
      
        RegistrarGatos registrarGatos = new RegistrarGatos();
        registrarGatos.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonRegistrarGatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerGatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerGatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerGatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerGatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerGatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrarGatos;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVolverAtras;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPersonaACargo;
    private javax.swing.JLabel jLabelRaza;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelWallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableGatos;
    private javax.swing.JTextField textCuidador;
    private javax.swing.JTextField textEdadGato;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textRaza;
    private javax.swing.JTextField textStatus;
    // End of variables declaration//GEN-END:variables

   }